version: '3'
services:

  polymer272:
    container_name: polymer272
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/polymer/app
    ports:
      - "8082:8081"
    networks:
      - app-network
    dns: 
      - 10.15.54.146

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local